/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.dai.swing.table;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author dainguyen
 */
public class HanhDong extends javax.swing.JPanel {

    /**
     * Creates new form HanhDong
     *
     * @param data
     */
    public HanhDong(ModelAction data) {
        initComponents();
        cmd_1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                if (data.getEventNguoiMua() != null) {
                    data.getEventNguoiMua().banRemoved(data.getKhachHang());
                } else {
                    System.out.println("Lỗi: EventActionNguoiMua chưa được khởi tạo!");
                }
            }
        });
        cmd_2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                if (data.getEventNguoiMua() != null) {
                    data.getEventNguoiMua().ban(data.getKhachHang());
                } else {
                    System.out.println("Lỗi: EventActionNguoiMua chưa được khởi tạo!");
                }
            }
        });

        cmd_1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                if (data.getEventNguoiBan() != null) {
                    data.getEventNguoiBan().banRemoved(data.getNguoiBan());
                } else {
                    System.out.println("Lỗi: EventActionNguoiBan chưa được khởi tạo!");
                }
            }
        });
        cmd_2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                if (data.getEventNguoiBan() != null) {
                    data.getEventNguoiBan().ban(data.getNguoiBan());
                } else {
                    System.out.println("Lỗi: EventActionNguoiBan chưa được khởi tạo!");
                }
            }
        });

        cmd_1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                if (data.getEventDuyetNguoiBan() != null) {
                    data.getEventDuyetNguoiBan().duyet(data.getDuyetNguoiBan());
                } else {
                    System.out.println("Lỗi: EventActionDuyetNguoiBan chưa được khởi tạo!");
                }
            }
        });
        cmd_2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                if (data.getEventDuyetNguoiBan() != null) {
                    data.getEventDuyetNguoiBan().huyDuyet(data.getDuyetNguoiBan());
                } else {
                    System.out.println("Lỗi: EventActionDuyetNguoiBan chưa được khởi tạo!");
                }
            }
        });

    }

    @Override
    protected void paintComponent(Graphics grphcs) {
        super.paintComponent(grphcs);
        grphcs.setColor(new Color(230, 230, 230));
        grphcs.drawLine(0, getHeight() - 1, getWidth(), getHeight() - 1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmd_1 = new com.dai.swing.Button();
        cmd_2 = new com.dai.swing.Button();

        cmd_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/dai/icon/check.png"))); // NOI18N
        cmd_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_1ActionPerformed(evt);
            }
        });

        cmd_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/dai/icon/ban.png"))); // NOI18N
        cmd_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmd_1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmd_2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmd_2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmd_1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmd_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmd_2ActionPerformed

    private void cmd_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmd_1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.dai.swing.Button cmd_1;
    private com.dai.swing.Button cmd_2;
    // End of variables declaration//GEN-END:variables
}
